name: Helm Drift Detection

on:
  pull_request:
    branches:
      - main
    paths:
      - 'desired.yaml'
      - '.github/workflows/**'
      - 'scripts/**'

jobs:
  drift-detection:
    name: Helm Drift Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: exchange-sandbox-2f1f

      - name: Authenticate and Connect to GKE cluster
        run: |
          gcloud container clusters get-credentials cluster-1 \
            --region=us-central1 \
            --project=exchange-sandbox-2f1f

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yq
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Run drift detection script
        run: |
          chmod +x ./scripts/detect-drift.sh
          ./scripts/detect-drift.sh

      - name: Upload drift report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: drift-report
          path: drift.log

      - name: Fail on drift detection
        if: failure()
        run: |
          echo "DRIFT DETECTED"
          exit 1
