name: Helm Drift Detection

on:
  pull_request:
    branches:
      - main

jobs:
  drift-detection:
    name: Detect Drift Between Desired and Live HPA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: Set GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: cluster-1
          location: us-central1
          project_id: exchange-sandbox-2f1f

      - name: Install Helm and yq
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          sudo snap install yq

      - name: Run Drift Detection Script
        run: |
          bash ./scripts/detect-drift.sh ./desired.yaml

      - name: Upload Drift Report
        uses: actions/upload-artifact@v4
        with:
          name: drift-log
          path: drift.log

      - name: Fail on Drift
        if: failure()
        run: echo "Drift detected! Failing the build." && exit 1
