name: Helm Drift Detection

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Helm-Drift-Detector/**'
      - '.github/workflows/**'
   
    paths-ignore:
      - 'Helm-Drift-Detector/Helm-Drift-Detection/Helm-Detection/reports/**'

permissions:
  contents: write          
  pull-requests: write

env:
  WORKDIR: Helm-Drift-Detector/Helm-Drift-Detection/Helm-Detection

jobs:
  detect-drift:
    name: Detect Drift in HPA/Service Config
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout Repo
        uses: actions/checkout@v4

      - name:  Authenticate to GCP (uses your JSON secret)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name:  Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: cluster-1
          location: us-central1
          project_id: exchange-sandbox-2f1f

      - name:  Install Helm + yq
        run: |
          curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          YQ_VERSION=v4.44.3
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          helm version && yq --version

      - name:  Debug & verify files
        run: |
          set -euxo pipefail
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          echo "---- Listing $WORKDIR ----"
          ls -la "$WORKDIR"
          echo "---- find detect-drift & desired.yaml ----"
          find "$WORKDIR" -maxdepth 3 -type f \( -name "detect-drift.sh" -o -name "desired.yaml" \) -print
          test -f "$WORKDIR/scripts/detect-drift.sh"
          test -f "$WORKDIR/desired.yaml" || (echo "desired.yaml missing in $WORKDIR" && exit 2)
          chmod +x "$WORKDIR/scripts/detect-drift.sh"

      - name:  Run Drift Detection Script
        working-directory: ${{ env.WORKDIR }}
        run: |
          set -euxo pipefail
          bash ./scripts/detect-drift.sh ./desired.yaml | tee drift.log

      - name:  Upload Drift Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: drift-report
          path: ${{ github.workspace }}/${{ env.WORKDIR }}/drift.log

 

      - name:  Build CSV drift report
        if: always()
        working-directory: ${{ env.WORKDIR }}
        run: |
          set -euo pipefail
          chmod +x ./scripts/log_to_csv.sh
          ./scripts/log_to_csv.sh   # reads drift.log, writes reports/drift_report_<ts>.csv

      - name:  Commit CSV to PR branch
        if: always() && github.event.pull_request.head.repo.full_name == github.repository
        run: |
          set -euxo pipefail
          BRANCH='${{ github.event.pull_request.head.ref }}'
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.WORKDIR }}/reports/*
          git diff --cached --quiet && echo "No report changes to commit" && exit 0
          git commit -m "chore(drift): add CSV report for ${{ github.sha }} [skip ci]"
          git push origin "HEAD:${BRANCH}"

      - name:  Fail PR if Drift Detected
        if: failure()
        run: |
          echo " DRIFT DETECTED. Failing build."
          exit 1
